//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealtimeBlendDemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealtimeBlendDemo.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Nokia example application demonstrating the real-time use of the blend effect provided by the Nokia Imaging SDK, the effect being applied to a stream of images received from the phone&apos;s camera..
        /// </summary>
        public static string AboutPage_AboutRun {
            get {
                return ResourceManager.GetString("AboutPage_AboutRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.github.com/nokia-developer/real-time-blend-demo/.
        /// </summary>
        public static string AboutPage_Hyperlink_Project {
            get {
                return ResourceManager.GetString("AboutPage_Hyperlink_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information and application source code go to {0}..
        /// </summary>
        public static string AboutPage_ProjectRun {
            get {
                return ResourceManager.GetString("AboutPage_ProjectRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPage_Title {
            get {
                return ResourceManager.GetString("AboutPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-time Blend Demo version {0}.
        /// </summary>
        public static string AboutPage_VersionRun {
            get {
                return ResourceManager.GetString("AboutPage_VersionRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REAL-TIME BLEND DEMO.
        /// </summary>
        public static string Application_Title {
            get {
                return ResourceManager.GetString("Application_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Filter_Blend_Add {
            get {
                return ResourceManager.GetString("Filter_Blend_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Filter_Blend_Color {
            get {
                return ResourceManager.GetString("Filter_Blend_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorburn.
        /// </summary>
        public static string Filter_Blend_Colorburn {
            get {
                return ResourceManager.GetString("Filter_Blend_Colorburn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colordodge.
        /// </summary>
        public static string Filter_Blend_Colordodge {
            get {
                return ResourceManager.GetString("Filter_Blend_Colordodge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darken.
        /// </summary>
        public static string Filter_Blend_Darken {
            get {
                return ResourceManager.GetString("Filter_Blend_Darken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference.
        /// </summary>
        public static string Filter_Blend_Difference {
            get {
                return ResourceManager.GetString("Filter_Blend_Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusion.
        /// </summary>
        public static string Filter_Blend_Exclusion {
            get {
                return ResourceManager.GetString("Filter_Blend_Exclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardlight.
        /// </summary>
        public static string Filter_Blend_Hardlight {
            get {
                return ResourceManager.GetString("Filter_Blend_Hardlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue.
        /// </summary>
        public static string Filter_Blend_Hue {
            get {
                return ResourceManager.GetString("Filter_Blend_Hue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighten.
        /// </summary>
        public static string Filter_Blend_Lighten {
            get {
                return ResourceManager.GetString("Filter_Blend_Lighten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiply.
        /// </summary>
        public static string Filter_Blend_Multiply {
            get {
                return ResourceManager.GetString("Filter_Blend_Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Filter_Blend_Normal {
            get {
                return ResourceManager.GetString("Filter_Blend_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlay.
        /// </summary>
        public static string Filter_Blend_Overlay {
            get {
                return ResourceManager.GetString("Filter_Blend_Overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen.
        /// </summary>
        public static string Filter_Blend_Screen {
            get {
                return ResourceManager.GetString("Filter_Blend_Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Softlight.
        /// </summary>
        public static string Filter_Blend_Softlight {
            get {
                return ResourceManager.GetString("Filter_Blend_Softlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Filter_None {
            get {
                return ResourceManager.GetString("Filter_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string MainPage_AboutPageButton {
            get {
                return ResourceManager.GetString("MainPage_AboutPageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} FPS.
        /// </summary>
        public static string MainPage_FrameRateCounter_Format {
            get {
                return ResourceManager.GetString("MainPage_FrameRateCounter_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next effect.
        /// </summary>
        public static string MainPage_NextEffectButton {
            get {
                return ResourceManager.GetString("MainPage_NextEffectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous effect.
        /// </summary>
        public static string MainPage_PreviousEffectButton {
            get {
                return ResourceManager.GetString("MainPage_PreviousEffectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing camera....
        /// </summary>
        public static string MainPage_Status_InitializingCamera {
            get {
                return ResourceManager.GetString("MainPage_Status_InitializingCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing camera failed, try restarting the application.
        /// </summary>
        public static string MainPage_Status_InitializingCameraFailed {
            get {
                return ResourceManager.GetString("MainPage_Status_InitializingCameraFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change texture.
        /// </summary>
        public static string MainPage_TextureButton {
            get {
                return ResourceManager.GetString("MainPage_TextureButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REAL-TIME BLEND DEMO - SELECT TEXTURE.
        /// </summary>
        public static string TexturePage_Application_Title {
            get {
                return ResourceManager.GetString("TexturePage_Application_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select texture.
        /// </summary>
        public static string TexturePage_Title {
            get {
                return ResourceManager.GetString("TexturePage_Title", resourceCulture);
            }
        }
    }
}
